# Generated by Django 4.1.7 on 2023-05-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAW', '0002_rename_id_port_agent_pool_ip_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_pool',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='使用中'),
        ),
        migrations.AlterField(
            model_name='agent_pool',
            name='is_ky',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
    ]
