# Generated by Django 4.1.7 on 2023-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_k_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_list',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock_list',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='股票代码'),
        ),
    ]
