# Generated by Django 4.1.7 on 2023-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stock_list_is_cyb_alter_stock_list_is_kcb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_list',
            old_name='stock_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='stock_list',
            old_name='stock_name',
            new_name='code_name',
        ),
        migrations.RenameField(
            model_name='stock_list',
            old_name='stock_industry',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='stock_list',
            old_name='stock_industryClassification',
            new_name='industryClassification',
        ),
        migrations.RenameField(
            model_name='stock_list',
            old_name='update',
            new_name='updateDate',
        ),
    ]
