# Generated by Django 2.2.16 on 2023-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stock_k_data_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_MA_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('date', models.DateField(verbose_name='日期')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='股票代码')),
                ('close', models.FloatField(null=True, verbose_name='收盘价')),
                ('MA_5', models.FloatField(null=True, verbose_name='MA_5')),
                ('MA_10', models.FloatField(null=True, verbose_name='MA_10')),
                ('MA_20', models.FloatField(null=True, verbose_name='MA_20')),
                ('MA_30', models.FloatField(null=True, verbose_name='MA_30')),
                ('MA_60', models.FloatField(null=True, verbose_name='MA_60')),
                ('MA_120', models.FloatField(null=True, verbose_name='MA_120')),
                ('MA_180', models.FloatField(null=True, verbose_name='MA_180')),
                ('MA_360', models.FloatField(null=True, verbose_name='MA_360')),
            ],
            options={
                'verbose_name': 'MA指标数据',
                'db_table': 'stock_MA_data',
            },
        ),
    ]
