# Generated by Django 4.1.7 on 2023-03-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_stock_list_table_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_data',
        ),
    ]
