# Generated by Django 4.1.7 on 2023-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_list',
            name='is_cyb',
            field=models.BooleanField(default=False, verbose_name='是否创业板'),
        ),
        migrations.AddField(
            model_name='stock_list',
            name='is_kcb',
            field=models.BooleanField(default=False, verbose_name='是否科创板'),
        ),
    ]
