# Generated by Django 4.1.7 on 2023-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_list_k_data_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_k_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('date', models.DateField(verbose_name='日期')),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('preclose', models.FloatField(verbose_name='昨日收盘价')),
                ('volume', models.IntegerField(verbose_name='成交数量')),
                ('amount', models.FloatField(verbose_name='成交金额')),
                ('adjustflag', models.CharField(max_length=10, verbose_name='复权状态')),
                ('turn', models.FloatField(verbose_name='换手率')),
                ('tradestatus', models.CharField(max_length=10, verbose_name='交易状态')),
                ('pctChg', models.FloatField(verbose_name='涨跌幅')),
                ('isST', models.CharField(max_length=10, verbose_name='是否ST')),
            ],
            options={
                'verbose_name': 'K线数据',
                'db_table': 'stock_k_data',
            },
        ),
    ]
