# Generated by Django 4.1.7 on 2023-03-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stock_list_id_alter_stock_list_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_list',
            name='stock_industry',
            field=models.CharField(max_length=8, null=True, verbose_name='行业类别'),
        ),
    ]
