# Generated by Django 4.1.7 on 2023-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stock_list_stock_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_list',
            name='is_cyb',
            field=models.BooleanField(default=False, null=True, verbose_name='是否创业板'),
        ),
        migrations.AlterField(
            model_name='stock_list',
            name='is_kcb',
            field=models.BooleanField(default=False, null=True, verbose_name='是否科创板'),
        ),
    ]
