# Generated by Django 4.1.7 on 2023-03-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stock_k_data_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_k_data',
            name='adjustflag',
            field=models.CharField(max_length=10, null=True, verbose_name='复权状态'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='amount',
            field=models.FloatField(null=True, verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='close',
            field=models.FloatField(null=True, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='high',
            field=models.FloatField(null=True, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='isST',
            field=models.CharField(max_length=10, null=True, verbose_name='是否ST'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='low',
            field=models.FloatField(null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='open',
            field=models.FloatField(null=True, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='pctChg',
            field=models.FloatField(null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='preclose',
            field=models.FloatField(null=True, verbose_name='昨日收盘价'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='tradestatus',
            field=models.CharField(max_length=10, null=True, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='stock_k_data',
            name='volume',
            field=models.IntegerField(null=True, verbose_name='成交数量'),
        ),
    ]
