# Generated by Django 4.1.7 on 2023-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_delete_stock_k_data_delete_stock_ma_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategic_Stock_Selection_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('date', models.DateField(verbose_name='日期')),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('selection_strategy', models.CharField(max_length=10, verbose_name='选择策略')),
            ],
            options={
                'verbose_name': '策略选股表',
                'db_table': 'strategic_stock_selection_table',
            },
        ),
    ]
