# Generated by Django 4.1.7 on 2023-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amazon_Best_Sellers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("category", models.CharField(max_length=255, verbose_name="类目名称")),
                ("product_title", models.TextField(null=True, verbose_name="商品标题")),
                ("rank", models.IntegerField(null=True, verbose_name="排名")),
                (
                    "ASIN",
                    models.CharField(max_length=255, null=True, verbose_name="ASIN"),
                ),
                (
                    "brand",
                    models.CharField(max_length=255, null=True, verbose_name="品牌"),
                ),
                (
                    "days30_parent",
                    models.CharField(
                        max_length=255, null=True, verbose_name="近30天销量(父体)"
                    ),
                ),
                ("score", models.IntegerField(null=True, verbose_name="评分")),
                ("score_count", models.IntegerField(null=True, verbose_name="评分数")),
                ("lsting_time", models.DateField(null=True, verbose_name="上架时间")),
                ("selling_price", models.FloatField(null=True, verbose_name="销售价格($)")),
            ],
            options={
                "verbose_name": "亚马逊销量排行榜",
                "db_table": "amazon_best_sellers",
            },
        ),
        migrations.CreateModel(
            name="ymx_url_list",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("category", models.CharField(max_length=255, verbose_name="类目名称")),
                (
                    "url_address",
                    models.CharField(max_length=255, null=True, verbose_name="链接地址"),
                ),
                (
                    "is_execute",
                    models.BooleanField(default=False, null=True, verbose_name="执行中"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, null=True, verbose_name="已执行"),
                ),
            ],
            options={
                "verbose_name": "亚马逊链接列表",
                "db_table": "ymx_ljlb",
            },
        ),
    ]
